services:
  - type: web
    name: omile-portal
    env: docker
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader && php artisan config:cache && php artisan route:cache && php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: OMILE
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_LEVEL
        value: error
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        fromDatabase:
          name: omile-db
          property: connectionString
      - key: MIDTRANS_CLIENT_KEY
        sync: false
      - key: MIDTRANS_SERVER_KEY
        sync: false
      - key: MIDTRANS_IS_PRODUCTION
        value: "false"

databases:
  - name: omile-db
    plan: free
    databaseName: omile
    user: omile_user

